DROP TABLE IF EXISTS SPITTER;
CREATE TABLE SPITTER (
  id        INT AUTO_INCREMENT,
  username  VARCHAR(255),
  password  VARCHAR(255),
  firstName VARCHAR(255),
  lastName  VARCHAR(255),
  PRIMARY KEY (id)
)